apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: message-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: '__REPO_URL__' #Placeholder to be replaced from the github workflow
    targetRevision: HEAD  
    path: 'app-manifests' 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: message-api  
  syncPolicy:
    automated:
      prune: true  # Delete resources, if removed from git
      selfHeal: true  # reconciling changes automatically
